### ISSUE TITLE
Editing what you see for a reference

### ISSUE THREAD

**Issue by julia-riley** [mjwestgate/revtools#11]
Would it be possible to create a "blind" option for revtools that when you click it you cannot see the authors names/affiliations? Or perhaps there already is this, but I don't know how to use it. Thanks.

**Comment by mjwestgate** [comment]
Hi Julia - Sorry for not getting back to you sooner, but this is now built into revtools by default. So all the apps hide identifying information by default, but you can display it again by setting 'hide identifying information' (in the 'display' tab) to false ![see the screenshot here for an example](https://user-images.githubusercontent.com/8155991/45608531-cd7a3880-ba96-11e8-814c-5d7c0a4fe6ee.png) Thanks for the suggestion! M
