### ISSUE TITLE
compatibility issues with Web of Science .ciw files

### ISSUE THREAD

**Issue by befriendabacterium** [mjwestgate/revtools#14]
revtools seems to have trouble handling .ciw file from Web of Science (EndNote Desktop Export option). Get error message:

'Error in data.frame(start = which(z.dframe$ris == "TY"), end = which(z.dframe$ris ==  : 
  arguments imply differing number of rows: 0, 467'

**Comment by mjwestgate** [comment]
Thanks for this Matt - I've fixed the error and tested it on a couple of datasets - let me know if you still have any problems and I'll revisit
