### ISSUE TITLE
Importing other formats

### ISSUE THREAD

**Issue by antnazNaz** [mjwestgate/revtools#27]
Is the package flexible enough to allow for the import of search results that are saved as xls/csv files?

**Comment by mjwestgate** [comment]
revtools can import .csv natively via `read_bibliography()`, which acts as a wrapper to `read.csv()`, plus a bit of correction to match the formatting for .bib and .ris file imports. It can't import xls/xlsx, but I'd suggest [readxl](https://readxl.tidyverse.org) for that.
