### ISSUE TITLE
Fails to install in R version 3.4.4

### ISSUE THREAD

**Issue by karahosford** [mjwestgate/revtools#28]
Attempting to install directly or via metaverse results in a failure:

> install.packages("revtools")
Installing package into ‘/home/user/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘revtools’ is not available (for R version 3.4.4)

**Comment by mjwestgate** [comment]
Hi Kevin,

Yeah that's not unexpected as revtools is restricted to R versions 3.5.0 or greater. This isn't for any particular reason - it's possible that it would work on earlier versions if I changed the defaults - but I haven't tested it on older versions of R. Is there any reason not to simply update to a more recent version?

Martin
