### ISSUE TITLE
SUBDOMAIN GOT HIJACK TO MAKE GAMBLING ONLINE AND SPAM

### ISSUE THREAD

**Issue by OLIV853** [mjwestgate/revtools#46]
![1](https://github.com/mjwestgate/revtools/assets/153894964/81fa0ebb-0b57-487d-a547-2db37e0d53a4)

Hello Sir,

I want to inform that  Your Server site already got hacked to make so many sub domain for gambling online site that's ilegal to do.

You can check in google use this keyword :
slot site:revtools.net

it will display so many this is serveral of the links:
http://jaminjp.revtools.net/surat4d.html

The button link is direct to gambling online site and only can access use indonesia IP address :
https://pub-bd37b0dd825d41f394c9cd3ee4530c96.r2.dev/index.html
https://t.ly/XlwoO
https://66kbet3m.top/

Please Remove,Banned also Track the Hacker and make the Hacker go to Jail.

As an Indonesian citizen, I want to emphasize that online gambling is clearly prohibited by Indonesian law. In accordance with Article 27 paragraph (2) of the ITE Law, this act is a prohibited act. Therefore, individuals are prohibited from distributing, transmitting or making accessible gambling content online.

I have attached clear photographic evidence related to this case. My request is that you immediately take the necessary action to delete this sub-domain and online gambling page, or at least suspend access immediately so that online gambling content cannot be accessed. I hope that firm steps will be taken to ensure the integrity of the father's name is maintained and to avoid potential legal problems in the future.

I am grateful for the attention and action taken regarding this matter. I am sure that you will uphold ethics and legal compliance in carrying out your services.

Yours faithfully,

**Comment by mjwestgate** [comment]
OK thanks for this. I've deactivated the site, and will see what else I can do to prevent it being used this way again.
