### ISSUE TITLE
Error in importing RDS after manipulating with "Include" or "Exclude" options

### ISSUE THREAD

**Issue by KBerthon** [mjwestgate/revtools#7]
My bibliography reads fine, but when I save an RDS from the shiny GUI after having selected articles to "include" or "exclude", and then try to re-import the RDS to start_review_window () I get the following error (the example is given when I had excluded one article):

Error in data.frame(id = rownames(dtm), label = info$label[which(x_keep)],  : 
  arguments imply differing number of rows: 802, 801

I think it must be something to do with how the exclusions are coded? It is a frustrating error because it means I must manipulate my data in the one sitting to avoid repeats when using the GUI to interrogate the references.

Thanks,
KatB

**Comment by mjwestgate** [comment]
Hi Kat,

Thanks for getting in touch! Sorry you're having trouble with revtools. I've had a quick look and can't duplicate your error with the datasets I've got here - would you mind sending me the file that you're having trouble with? Either the .rds or the initial file you imported from would probably be fine. Otherwise it's difficult to know precisely how to fix the problem.

Thanks,
Martin

**Comment by KBerthon** [comment]
Hi Martin,

I just tried again this morning and it all worked fine. This was an error I
had a while ago and only just got around to posting so must have had a
mistake in my bibliography files that I have since fixed. Sorry to throw
you a red herring!

Thanks,
KatB

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-6594620056760887720_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mjwestgate** [comment]
OK, great! Thanks for getting in touch, and let me know if you spot any other bugs - it's always good to have feedback from new users! M
